### ISSUE TITLE
在跑demo时发现的几个问题

### ISSUE THREAD

**Issue by hhbusui** [18888628835/react-drag-resizable#2]
大佬今天在使用您的组件时候遇到几个疑问能否解答呢

1.  如何更改吸附线的颜色
2.  如何更改8个小方框的颜色
3.  可以暴露dragStart dragEnd方法么

其他
1. 两个元素组合
2. 元素置顶置底

**Comment by 18888628835** [comment]
> 



> 

吸附线的颜色跟 8 个小方块都可以通过 css 来修改噢，dragStart 和 dragEnd 方法可以暴露，这个功能我会尽快放上去然后告知您。

至于两个元素组合和元素置顶置底，不是很明白您想要的是怎样的功能？

**Comment by 18888628835** [comment]
> 大佬今天在使用您的组件时候遇到几个疑问能否解答呢
> 
> 1. 如何更改吸附线的颜色
> 2. 如何更改8个小方框的颜色
> 3. 可以暴露dragStart dragEnd方法么
> 
> 其他
> 
> 1. 两个元素组合
> 2. 元素置顶置底

介于您的需求，我会额外增加一些 API 来修改吸附线样式以及小方块的样式。到时候您就不需要用 css 覆盖了

**Comment by h1530687053** [comment]
好的谢谢大佬。样式我是可以改的，但是希望您提供API这样方便一点。

**Comment by hhbusui** [comment]
两个元素组合和元素置顶置底

> > 
> 
> > 
> 
> 吸附线的颜色跟 8 个小方块都可以通过 css 来修改噢，dragStart 和 dragEnd 方法可以暴露，这个功能我会尽快放上去然后告知您。
> 
> 至于两个元素组合和元素置顶置底，不是很明白您想要的是怎样的功能？

两个元素组合和元素置顶置底

> > 大佬今天在使用您的组件时候遇到几个疑问能否解答呢
> > 
> > 1. 如何更改吸附线的颜色
> > 2. 如何更改8个小方框的颜色
> > 3. 可以暴露dragStart dragEnd方法么
> > 
> > 其他
> > 
> > 1. 两个元素组合
> > 2. 元素置顶置底
> 
> 介于您的需求，我会额外增加一些 API 来修改吸附线样式以及小方块的样式。到时候您就不需要用 css 覆盖了

好的感谢大佬，这样就很方便了。

**Comment by hhbusui** [comment]
> > 
> 
> > 
> 
> 吸附线的颜色跟 8 个小方块都可以通过 css 来修改噢，dragStart 和 dragEnd 方法可以暴露，这个功能我会尽快放上去然后告知您。
> 
> 至于两个元素组合和元素置顶置底，不是很明白您想要的是怎样的功能？

这两个需求是我自己这边的需求，可能我问错了。就是(https://js.design/)这种原型设计上用的图层置顶和置底，分组和解除分组。大佬您有什么好的实现方式或者插件么？

**Comment by 18888628835** [comment]
> > > 
> > 
> > 
> > > 
> > 
> > 
> > 吸附线的颜色跟 8 个小方块都可以通过 css 来修改噢，dragStart 和 dragEnd 方法可以暴露，这个功能我会尽快放上去然后告知您。
> > 至于两个元素组合和元素置顶置底，不是很明白您想要的是怎样的功能？
> 
> 这两个需求是我自己这边的需求，可能我问错了。就是([https://js.design/)这种原型设计上用的图层置顶和置底，分组和解除分组。大佬您有什么好的实现方式或者插件么？](https://js.design/)%E8%BF%99%E7%A7%8D%E5%8E%9F%E5%9E%8B%E8%AE%BE%E8%AE%A1%E4%B8%8A%E7%94%A8%E7%9A%84%E5%9B%BE%E5%B1%82%E7%BD%AE%E9%A1%B6%E5%92%8C%E7%BD%AE%E5%BA%95%EF%BC%8C%E5%88%86%E7%BB%84%E5%92%8C%E8%A7%A3%E9%99%A4%E5%88%86%E7%BB%84%E3%80%82%E5%A4%A7%E4%BD%AC%E6%82%A8%E6%9C%89%E4%BB%80%E4%B9%88%E5%A5%BD%E7%9A%84%E5%AE%9E%E7%8E%B0%E6%96%B9%E5%BC%8F%E6%88%96%E8%80%85%E6%8F%92%E4%BB%B6%E4%B9%88%EF%BC%9F)

置顶和置底可以通过 z-index 控制层叠关系，至于分组和解除分组功能，貌似我在 moveable 上看到过，[moveable-group](https://daybrush.com/moveable/storybook/index.html?path=/story/group--draggable),你看看是不是你需要的呢

**Comment by hhbusui** [comment]
> > > > 
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > 并且很喜欢把这个小方块的颜色跟8个置顶一起修改，来个置顶，然后我就可以先把这个功能放在
> > > 上面想要怎样的功能？
> > 
> > 
> > 这是我需要的两个人的需求，可能是我的需求[。您有什么好的实现方式或者插件么？](https://js.design/) %E8%BF%99%E7%A7%8D%E5%8E%9F%E5%9E%8B%E8%AE%BE%E8%AE%A1%E4% B8%8A%E7%94%A8%E7%9A%84%E5%9B%BE%E5%B1%82%E7%BD%AE%E9%A1%B6%E5%92%8C%E7%BD% AE%E5%BA%95%EF%BC%8C%E5%88%86%E7%BB%84%E5%92%8C%E8%A7%A3%E9%99%A4%E5%88%86% E7%BB%84%E3%80%82%E5%A4%A7%E4%BD%AC%E6%82%A8%E6%9C%89%E4%BB%80%E4%B9%88%E5% A5%BD%E7%9A%84%E5%AE%9E%E7%8E%B0%E6%96%B9%E5%BC%8F%E6%88%96%E8%80%85%E6%8F% 92%E4%BB%B6%E4%B9%88%EF%BC%9F)
> 
> 顶和置顶可以通过控制组显示关系，至于我和置顶功能，可以在上面移动，看起来[不是](https://daybrush.com/moveable/storybook/index.html?path=/story/group--draggable)你的呢？

推荐的这个组件挺好的，基本满足需求了。谢谢大佬
